name: Secure Flask CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decrypt encrypted password file using AWS KMS
      run: |
        aws kms decrypt \
          --ciphertext-blob fileb://encrypted_passwords \
          --output text \
          --query Plaintext | base64 --decode > .env
          
    - name: Run Flask App
      run: |
        pip install -r requirements.txt
        python app.py
